import { useState } from 'react';
import { Alert, StyleSheet, Text, View } from 'react-native';
import { useAuth } from '@/features/auth/auth-provider';
import { useActivateAiPlanMutation, useCreateAiPlanMutation, useWorkspaceQuery } from '@/features/workspace/workspace-query';
import { disciplineTheme } from '@/shared/theme';
import { AppButton, AppCard, AppInput, FormField, ScreenContainer, SectionHeader } from '@/shared/ui';

export function AiPlannerScreen() {
  const { token } = useAuth(); const query = useWorkspaceQuery(token); const create = useCreateAiPlanMutation(token ?? ''); const activate = useActivateAiPlanMutation(token ?? '');
  const [dream, setDream] = useState(''); const [situation, setSituation] = useState(''); const [obstacle, setObstacle] = useState(''); const [roleModel, setRoleModel] = useState(''); const [error, setError] = useState<string | null>(null);
  function submit() { if (dream.trim().length < 5) return setError('Describe your dream in at least five characters.'); setError(null); create.mutate({ dream: dream.trim(), ...(situation.trim() ? { currentSituation: situation.trim() } : {}), ...(obstacle.trim() ? { mainObstacle: obstacle.trim() } : {}), ...(roleModel.trim() ? { roleModel: roleModel.trim() } : {}) }, { onSuccess: () => { setDream(''); setSituation(''); setObstacle(''); setRoleModel(''); } }); }
  function activatePlan(id: string) { Alert.alert('Activate this plan?', 'This creates real goals, habits, and reminders from the suggestions.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Activate', onPress: () => activate.mutate(id) }]); }
  return <ScreenContainer contentStyle={styles.content} refreshing={query.isRefetching} onRefresh={() => void query.refetch()}><SectionHeader eyebrow="AI Planner" title="Turn ambition into structure" subtitle="Generate a practical plan, review it, then activate it into real daily actions." /><AppCard><FormField label="Your dream" error={error}><AppInput multiline value={dream} onChangeText={setDream} maxLength={500} /></FormField><FormField label="Current situation"><AppInput multiline value={situation} onChangeText={setSituation} maxLength={1000} /></FormField><FormField label="Main obstacle"><AppInput multiline value={obstacle} onChangeText={setObstacle} maxLength={500} /></FormField><FormField label="Role model"><AppInput value={roleModel} onChangeText={setRoleModel} maxLength={200} /></FormField><AppButton loading={create.isPending} onPress={submit}>Generate discipline plan</AppButton></AppCard><SectionHeader eyebrow="Plans" title="Generated plans" />{(query.data?.aiPlans ?? []).map((plan) => <AppCard key={plan.id}><Text style={styles.title}>{plan.dream}</Text><Text style={styles.copy}>{plan.mentorStory}</Text><Text style={styles.label}>Suggested goals</Text>{plan.suggestedGoals.map((goal) => <Text key={goal.title} style={styles.item}>• {goal.title}</Text>)}<Text style={styles.label}>Suggested habits</Text>{plan.suggestedHabits.map((habit) => <Text key={habit.title} style={styles.item}>• {habit.title} · {habit.frequency}</Text>)}<Text style={styles.copy}>Replace “{plan.distractionStrategy.trigger}” with “{plan.distractionStrategy.replacementAction}”.</Text><AppButton loading={activate.isPending} onPress={() => activatePlan(plan.id)}>Activate plan</AppButton></AppCard>)}{!query.data?.aiPlans.length ? <AppCard><Text style={styles.copy}>No AI plans yet. Describe the outcome you want to build toward.</Text></AppCard> : null}</ScreenContainer>;
}
const styles = StyleSheet.create({ content: { gap: disciplineTheme.spacing.lg }, title: { color: disciplineTheme.colors.text, fontSize: 20, fontWeight: '900' }, copy: { color: disciplineTheme.colors.textMuted, fontSize: 14, lineHeight: 22 }, label: { color: disciplineTheme.colors.primary, fontSize: 12, fontWeight: '800', textTransform: 'uppercase' }, item: { color: disciplineTheme.colors.text, fontSize: 14, lineHeight: 22 } });
