export const disciplineTheme = {
  colors: {
    background: '#f6f8fb',
    surface: '#ffffff',
    surfaceMuted: '#f8fafc',
    surfaceRaised: '#ffffff',
    border: '#dbe3ef',
    borderStrong: '#c6d1e1',
    text: '#071124',
    textMuted: '#53627a',
    textFaint: '#7b8aa3',
    primary: '#4f46e5',
    primaryHover: '#4338ca',
    primarySoft: '#eef2ff',
    primaryText: '#ffffff',
    success: '#059669',
    successSoft: '#d1fae5',
    warning: '#f59e0b',
    warningSoft: '#fff3d6',
    danger: '#e11d48',
    dangerSoft: '#ffe4ec',
    brandSecondary: '#7c3aed',
    brandTertiary: '#0ea5e9',
  },
  radius: {
    sm: 10,
    md: 14,
    lg: 18,
    xl: 24,
    xxl: 28,
    pill: 999,
  },
  spacing: {
    xs: 6,
    sm: 10,
    md: 14,
    lg: 18,
    xl: 24,
    xxl: 32,
  },
  shadow: {
    card: {
      shadowColor: '#0f172a',
      shadowOpacity: 0.06,
      shadowOffset: { width: 0, height: 10 },
      shadowRadius: 30,
      elevation: 4,
    },
    strong: {
      shadowColor: '#1f2e55',
      shadowOpacity: 0.14,
      shadowOffset: { width: 0, height: 18 },
      shadowRadius: 44,
      elevation: 8,
    },
  },
} as const;

export type DisciplineTheme = typeof disciplineTheme;
